#!/system/bin/sh
cwd="$(dirname $(realpath $0))"
if [ -e "$cwd/newSubrip.srt" ]
then
rm -f "$cwd/newSubrip.srt"
fi
# 1

find $cwd/txt -name "*.txt" -type f > "$cwd/build.txt"
busybox echo -e "#!/system/bin/sh\n## Generated by $0\necho \"Executing \$0\"" > "$cwd/02-$(basename $0)"
cat "$cwd/build.txt"|busybox awk -v subrip="$@" '{print "cat " $0 " >> \$(dirname \$(realpath " subrip "))/new-\$(basename " subrip ")"}' >> $cwd/02-$(basename $0)
sh "$cwd/02-$(basename $0)"
echo "$0 is done"

