#!/system/bin/sh
fold="$(dirname $(realpath $0))"
#if [ ! -e "$fold/normaLaudio/NewLineBuilder.sh" ]
#then
#cat $fold/NewLineBuilder.sh > $fold/normaLaudio/NewLineBuilder.sh
#fi

echo "Finding many word in subrip files"
find $fold/txt -name "*.txt" -type f > $fold/split.txt
check="$(cat $fold/split.txt)"
if [ -z "$check" ]
then
echo "Please run $fold/build.txt.sh first"
kill -9 $$
fi

busybox echo -e "#!/system/bin/sh\n### generated by $0 ###" > "$fold/02-$(basename $0)"
cat $fold/split.txt|busybox awk -v folder=$fold '{print "sh " folder "/NewLineBuilder3.sh " $0}' >> "$fold/02-$(basename $0)"
sh "$fold/02-$(basename $0)"
echo "$0 is done"

