#!/system/bin/sh
cwd="$(dirname $(realpath $0))"
if [ -e "$cwd/new-$(basename $@)" ]
then
rm -f "$cwd/new-$(basename $0)"
fi
# 1
busybox echo -e "\nMengumpulkan kembali string ke subjudul\n"
find $cwd/txt -name "*.txt" -type f > "$cwd/build.txt"
cat $cwd/build.txt|busybox sort -n > $cwd/build-fo.txt
busybox echo -e "#!/system/bin/sh\n## Generated by $0\necho \"Executing \$0\"" > "$cwd/02-$(basename $0)"
cat "$cwd/build-fo.txt"|busybox awk -v subrip="$@" '{print "busybox cat " $0 " >> \$(dirname \$(realpath " subrip "))/new-\$(basename " subrip ")"}' >> $cwd/02-$(basename $0)
sh "$cwd/02-$(basename $0)"
busybox echo -e "Subjudul dengan garis baru selesai\n$0 selesai.\n" 
